name: Trivy check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-check:
    name: Trivy Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run trivy linter
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: '.'
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          
